# Generated by Django 4.0.2 on 2022-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_shop_user',
            field=models.BooleanField(default=False),
        ),
    ]
