# Generated by Django 4.0.2 on 2022-02-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_myuser_is_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_shop_user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='roles',
            field=models.CharField(default='customer', max_length=10),
        ),
    ]
