# Generated by Django 4.0.2 on 2022-02-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_user_delete_myuser_delete_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shopdesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shopname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
