# Generated by Django 4.0.2 on 2022-02-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0014_orderitems_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='provider',
        ),
    ]
