# Generated by Django 4.0.2 on 2022-03-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0016_orderitems_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(default='Waiting for delivery', max_length=50),
        ),
    ]
