# Generated by Django 4.0.2 on 2022-03-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0017_orderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soldcount',
            field=models.IntegerField(default=0),
        ),
    ]
