# Generated by Django 4.0.2 on 2022-03-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0018_product_soldcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='customer', max_length=10),
        ),
    ]
