# Generated by Django 4.0.2 on 2022-03-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0022_remove_product_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='soldcount',
        ),
    ]
