# Generated by Django 4.0.2 on 2022-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0024_remove_order_date_remove_orderitems_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
